/*
export const first = {
  title: "",
  description: "",
  titleEN: "",
  descriptionEN: "",
  postScriptum: "",
  courses: [
      {
          title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",

      }
  ]
};
*/

const state = {
  appetisers: [
    {
      title: "ראשונות קרות",
      description: "",
      postScriptum: "",
      titleEN: "appetisers",
      descriptionEN: "",
      postScriptumEN: "",
      dishes: [
        {
          title: "סלט וואקאמה",
          description:
            "אצות וואקאמה, צנונית, מלפפון ובצל ברוטב וואפו (ניתן לבקש ללא גלוטן)",
          titleEN: "",
          descriptionEN: "",
          price: 24,
          isVegi: true,
          imgUrl: "",
        },
        {
          title: "סלט הרוסאמה",
          description:
            "אטריות תפוחי אדמה, מלפפון, בצל ירוק וסלמון ברוטב וואפו (ניתן לבקש ללא גלוטן)",
          titleEN: "",
          descriptionEN: "",
          price: 32,
          isVegi: false,
          imgUrl: "",
        },
        {
          title: "סלט מידורי",

          description:
            "סלט עלי חסה, רוקט, צנונית, מלפפון, תפוח, בצל ושקדים קלויים ברוטב למון ג'ויו (טבעוני, ללא גלוטן)",
          titleEN: "",
          descriptionEN: "",
          price: 52,
          isVegi: true,
          imgUrl: "",
        },
      ],
    },
    {
      title: "ראשונות חמות",
      description: "",
      postScriptum: "",
      titleEN: "appetisers",
      descriptionEN: "",
      postScriptumEN: "",
      dishes: [
        {
          title: "אדה ממה",
          description: "פולי סויה חלוטים ומומלחים (טבעוני ללא גלוטן)",
          titleEN: "",
          descriptionEN: "",
          price: 26,
          isVegi: true,
          imgUrl: "",
        },
        {
          title: "אומיסו שירו",
          description: "מרק מיסו עם אצות וואקאמה, טופו ובצל ירוק",
          titleEN: "",
          descriptionEN: "",
          price: 28,
          isVegi: false,
          imgUrl: "",
        },
        {
          title: "אגדאשי דופו",
          description:
            "קוביות טופו פריכות ברוטב טנצויו חם, צנון כתוש, בצל ירוק ופטריות נמקו (ניתן לבקש טבעוני)",
          titleEN: "",
          descriptionEN: "",
          price: [36, 44],
          isVegi: false,
          imgUrl: "",
        },
      ],
    },
  ],
  skewers: {
    title: "שיפודי עץ על הגריל",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "skewers",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  mainDishes: {
    title: "מנות עיקריות",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "main dishes",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  desserts: {
    title: "קינוחים",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "desserts",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  seshimi: {
    title: "סשימי / ניגירי",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "seshimi / nigiri",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  inari: {
    title: "אינרי / גונקן",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "inari / gunkan",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  hosomaki: {
    title: "הוסומקי",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "hosomaki",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  temaki: {
    title: "טמקי - קונוס",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "temaki",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  irodori: {
    title: "אירודורי - IO",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "irodori i/o",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  combinations: {
    title: "קומבינציות",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "combinations",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  lunch75: {
    title: "עסקית 75",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "lunch 75",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  lunch90: {
    title: "עסקית 90",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "lunch 90",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  lunch105: {
    title: "עסקית 105",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "lunch 105",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  wine: {
    title: "יינות",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "wine",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  sake: {
    title: "סאקה",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "sake & beer",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  coctails: {
    title: "קוקטיילים",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "coctails",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
  softDrinks: {
    title: "שתייה קלה",
    description: "עמוד בבניה",
    postScriptum: "",
    titleEN: "soft drinks",
    descriptionEN: "",
    postScriptumEN: "",
    dishes: [
      {
        title: "",
        description: "",
        titleEN: "",
        descriptionEN: "",
        price: 0,
        isVegi: false,
        imgUrl: "",
      },
    ],
  },
};
